/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GameScoreInterface extends Interface {
  getFunction(nameOrSignature: "recordScore"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ScoreRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "recordScore",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordScore",
    data: BytesLike
  ): Result;
}

export namespace ScoreRecordedEvent {
  export type InputTuple = [
    submitterAddress: AddressLike,
    winner: string,
    loser: string,
    score: string,
    duration: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    submitterAddress: string,
    winner: string,
    loser: string,
    score: string,
    duration: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    submitterAddress: string;
    winner: string;
    loser: string;
    score: string;
    duration: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameScore extends BaseContract {
  connect(runner?: ContractRunner | null): GameScore;
  waitForDeployment(): Promise<this>;

  interface: GameScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordScore: TypedContractMethod<
    [_winner: string, _loser: string, _score: string, _duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordScore"
  ): TypedContractMethod<
    [_winner: string, _loser: string, _score: string, _duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ScoreRecorded"
  ): TypedContractEvent<
    ScoreRecordedEvent.InputTuple,
    ScoreRecordedEvent.OutputTuple,
    ScoreRecordedEvent.OutputObject
  >;

  filters: {
    "ScoreRecorded(address,string,string,string,uint256,uint256)": TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
    ScoreRecorded: TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
  };
}
