/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GameScore } from "./GameScore";
export * as factories from "./factories";
export { GameScore__factory } from "./factories/GameScore__factory";
